// default package
// Generated Oct 18, 2019 10:06:43 AM by Hibernate Tools 5.2.12.Final
package com.korera.main.Entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.JoinColumn;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "Project", catalog = "KoreraSchema")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Project implements java.io.Serializable {

	private Integer projectId;
	private String projectName;
	private String extraCols;
	private String extraColsType;
	
//	@ManyToMany
//	@JoinTable(
//	  name = "ProjectResource", 
//	  joinColumns = @JoinColumn(name = "pid"), 
//	  inverseJoinColumns = @JoinColumn(name = "rid"))
//	List<Resource> listResources;
	
//	public Project() {
//	}
//
//	public Project(String projectName) {
//		this.projectName = projectName;
//	}
//
//	public Project(String projectName, String extraCols, String extraColsType) {
//		this.projectName = projectName;
//		this.extraCols = extraCols;
//		this.extraColsType = extraColsType;
//	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "projectID", unique = true, nullable = false)
	public Integer getProjectId() {
		return this.projectId;
	}

	@Column(name = "projectName", nullable = false, length = 256)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "extraCols", length = 256)
	public String getExtraCols() {
		return this.extraCols;
	}

	public void setExtraCols(String extraCols) {
		this.extraCols = extraCols;
	}

	@Column(name = "extraColsType", length = 256)
	public String getExtraColsType() {
		return this.extraColsType;
	}

	public void setExtraColsType(String extraColsType) {
		this.extraColsType = extraColsType;
	}
	
//	public List<Resource> getResources(){
//		return listResources;
//	}
//	
//	public void setResources(List<Resource> lr) {
//		this.listResources = lr;
//	}

}
