spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: Asdf1234.
      url: jdbc:mysql://localhost:3306/KoreraSchema?useSSL=false
   jpa:
      show-sql: true
server:
   servlet:
      context-path: /Korera